"""Add pgvector extension and embedding column to content_chunks

Revision ID: 72e6d86b204d
Revises: 9a3b7d2c1e5f
Create Date: 2025-12-01 11:33:09.456675

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72e6d86b204d"
down_revision: Union[str, Sequence[str], None] = "9a3b7d2c1e5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: enable pgvector extension and add embedding column."""
    # Enable pgvector extension (idempotent)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # Add embedding column using raw SQL (pgvector type not available in migration context)
    op.execute("ALTER TABLE content_chunks ADD COLUMN embedding vector(1536) NULL;")

    # Create IVFFlat index for cosine similarity search
    # lists parameter: recommended to be around 4 * sqrt(rows)
    # For initial deployment, use 100 lists (good for ~600K rows)
    op.execute(
        """
        CREATE INDEX content_chunks_embedding_cosine_idx
        ON content_chunks
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100);
        """
    )


def downgrade() -> None:
    """Downgrade schema: remove embedding column (keep pgvector extension)."""
    # Drop index
    op.execute("DROP INDEX IF EXISTS content_chunks_embedding_cosine_idx;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content_chunks", "embedding")
    # ### end Alembic commands ###

    # Note: We do NOT drop the pgvector extension on downgrade,
    # as it might be used by other tables/applications.
    # Extension remains in the database but unused.
