"""Remove canonical_version from documents and highlights

Revision ID: 7f08aad13a4d
Revises: ff2d3eadcd14
Create Date: 2025-11-28 18:00:18.718543

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f08aad13a4d"
down_revision: Union[str, Sequence[str], None] = "ff2d3eadcd14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("annotations", "highlight_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(
        op.f("idx_annotations_chunk"),
        table_name="annotations",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_index(op.f("ix_annotations_chunk_id"), table_name="annotations")
    op.drop_constraint(op.f("annotations_chunk_id_fkey"), "annotations", type_="foreignkey")
    op.drop_column("annotations", "chunk_id")
    op.drop_column("documents", "canonical_version")
    op.drop_column("highlights", "canonical_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "highlights",
        sa.Column("canonical_version", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column("canonical_version", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "annotations", sa.Column("chunk_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("annotations_chunk_id_fkey"), "annotations", "content_chunks", ["chunk_id"], ["id"]
    )
    op.create_index(op.f("ix_annotations_chunk_id"), "annotations", ["chunk_id"], unique=False)
    op.create_index(
        op.f("idx_annotations_chunk"),
        "annotations",
        ["chunk_id"],
        unique=False,
        postgresql_where="(deleted_at IS NULL)",
    )
    op.alter_column("annotations", "highlight_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
