"""Add anchored_content_hash to documents

Revision ID: 828847eeffa7
Revises: 7f08aad13a4d
Create Date: 2025-12-01 09:08:19.130628

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "828847eeffa7"
down_revision: Union[str, Sequence[str], None] = "7f08aad13a4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("anchored_content_hash", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "anchored_content_hash")
    # ### end Alembic commands ###
