"""Initial schema

Revision ID: ff2d3eadcd14
Revises: 
Create Date: 2025-11-28 17:34:50.830627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2d3eadcd14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('chunk_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('text_start', sa.BigInteger(), nullable=False),
    sa.Column('text_end', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("media_type IN ('document', 'episode', 'video')", name='ck_content_chunks_media_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_chunks_media', 'content_chunks', ['media_type', 'media_id'], unique=False)
    op.create_table('metadata_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('chunk_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('document', 'episode', 'video', 'podcast')", name='ck_metadata_chunks_entity_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metadata_chunks_entity', 'metadata_chunks', ['entity_type', 'entity_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_user_id', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_external_user_id', 'users', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_user_id'), 'users', ['external_user_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_state', sa.JSON(), nullable=True),
    sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_public', 'conversations', ['is_public'], unique=False, postgresql_where='is_public = TRUE AND deleted_at IS NULL')
    op.create_index('idx_conversations_user', 'conversations', ['user_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.String(length=10), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('original_blob_key', sa.Text(), nullable=False),
    sa.Column('original_mime_type', sa.String(length=100), nullable=False),
    sa.Column('original_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_version', sa.Integer(), nullable=False),
    sa.Column('text_byte_length', sa.Integer(), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retries_count', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('chunk_version', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("embedding_status IN ('pending', 'ready', 'failed')", name='ck_documents_embedding_status'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'ready', 'failed')", name='ck_documents_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_content_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('idx_documents_embedding_status', 'documents', ['embedding_status'], unique=False, postgresql_where="embedding_status != 'ready' AND deleted_at IS NULL")
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False, postgresql_where="status != 'ready' AND deleted_at IS NULL")
    op.create_index('idx_documents_user', 'documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('highlights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('anchor_type', sa.String(length=20), nullable=False),
    sa.Column('text_start', sa.BigInteger(), nullable=False),
    sa.Column('text_end', sa.BigInteger(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('suffix', sa.Text(), nullable=False),
    sa.Column('canonical_version', sa.Integer(), nullable=True),
    sa.Column('transcript_hash', sa.String(length=64), nullable=True),
    sa.Column('pdf_page_number', sa.Integer(), nullable=True),
    sa.Column('pdf_char_offset', sa.Integer(), nullable=True),
    sa.Column('pdf_extraction_confidence', sa.Float(), nullable=True),
    sa.Column('pdf_file_hash', sa.String(length=64), nullable=True),
    sa.Column('time_start', sa.Float(), nullable=True),
    sa.Column('time_end', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_detached', sa.Boolean(), nullable=False),
    sa.Column('detached_reason', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(anchor_type = 'text' AND pdf_page_number IS NULL AND pdf_char_offset IS NULL AND pdf_extraction_confidence IS NULL AND pdf_file_hash IS NULL AND time_start IS NULL AND time_end IS NULL) OR (anchor_type = 'pdf' AND pdf_page_number IS NOT NULL AND pdf_char_offset IS NOT NULL AND pdf_file_hash IS NOT NULL AND time_start IS NULL AND time_end IS NULL) OR (anchor_type = 'transcript' AND time_start IS NOT NULL AND time_end IS NOT NULL AND pdf_page_number IS NULL AND pdf_char_offset IS NULL AND pdf_extraction_confidence IS NULL AND pdf_file_hash IS NULL)", name='ck_highlights_anchor_type_validity'),
    sa.CheckConstraint("(media_type = 'document' AND anchor_type IN ('text', 'pdf')) OR (media_type IN ('episode', 'video') AND anchor_type = 'transcript')", name='ck_highlights_media_anchor_compatibility'),
    sa.CheckConstraint("(media_type = 'document' AND canonical_version IS NOT NULL AND transcript_hash IS NULL) OR (media_type IN ('episode', 'video') AND transcript_hash IS NOT NULL AND canonical_version IS NULL)", name='ck_highlights_version_anchor'),
    sa.CheckConstraint("anchor_type IN ('text', 'pdf', 'transcript')", name='ck_highlights_anchor_type'),
    sa.CheckConstraint("color IN ('yellow', 'blue', 'green', 'pink', 'purple')", name='ck_highlights_color'),
    sa.CheckConstraint("media_type IN ('document', 'episode', 'video')", name='ck_highlights_media_type'),
    sa.CheckConstraint('text_end > text_start', name='ck_highlights_text_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_highlights_anchor_type', 'highlights', ['anchor_type'], unique=False)
    op.create_index('idx_highlights_media', 'highlights', ['media_type', 'media_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_highlights_pdf', 'highlights', ['media_id', 'pdf_page_number'], unique=False, postgresql_where="anchor_type = 'pdf' AND deleted_at IS NULL")
    op.create_index('idx_highlights_transcript', 'highlights', ['media_id', 'time_start'], unique=False, postgresql_where="anchor_type = 'transcript' AND deleted_at IS NULL")
    op.create_index('idx_highlights_user', 'highlights', ['user_id'], unique=False, postgresql_where='NOT is_hidden AND deleted_at IS NULL')
    op.create_index(op.f('ix_highlights_user_id'), 'highlights', ['user_id'], unique=False)
    op.create_table('libraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_libraries_public', 'libraries', ['is_public'], unique=False, postgresql_where='is_public = TRUE')
    op.create_index('idx_libraries_user', 'libraries', ['user_id'], unique=False)
    op.create_index(op.f('ix_libraries_user_id'), 'libraries', ['user_id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('document', 'episode', 'video', 'highlight', 'annotation', 'message', 'conversation')", name='ck_links_valid_source_type'),
    sa.CheckConstraint("target_type IN ('document', 'episode', 'video', 'highlight', 'annotation', 'message', 'conversation')", name='ck_links_valid_target_type'),
    sa.CheckConstraint('NOT (source_type = target_type AND source_id = target_id)', name='ck_links_no_self_links'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', name='uq_links_canonical')
    )
    op.create_index('idx_links_creator', 'links', ['created_by_user_id'], unique=False)
    op.create_index('idx_links_source', 'links', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_links_target', 'links', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_links_created_by_user_id'), 'links', ['created_by_user_id'], unique=False)
    op.create_table('thought_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chunk_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("object_type IN ('annotation', 'message', 'conversation_summary')", name='ck_thought_chunks_object_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_thought_chunks_object', 'thought_chunks', ['object_type', 'object_id'], unique=False)
    op.create_index('idx_thought_chunks_user', 'thought_chunks', ['user_id'], unique=False)
    op.create_index(op.f('ix_thought_chunks_user_id'), 'thought_chunks', ['user_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('highlight_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(highlight_id IS NOT NULL AND chunk_id IS NULL) OR (highlight_id IS NULL AND chunk_id IS NOT NULL)', name='ck_annotations_exactly_one_anchor'),
    sa.ForeignKeyConstraint(['chunk_id'], ['content_chunks.id'], ),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_annotations_chunk', 'annotations', ['chunk_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_annotations_highlight', 'annotations', ['highlight_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_annotations_user', 'annotations', ['user_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_annotations_chunk_id'), 'annotations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_annotations_highlight_id'), 'annotations', ['highlight_id'], unique=False)
    op.create_index(op.f('ix_annotations_user_id'), 'annotations', ['user_id'], unique=False)
    op.create_table('library_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("media_type IN ('document', 'episode', 'video')", name='ck_library_media_type'),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'media_type', 'media_id', name='uq_library_media_library_media')
    )
    op.create_index('idx_library_media_library', 'library_media', ['library_id'], unique=False)
    op.create_index('idx_library_media_media', 'library_media', ['media_type', 'media_id'], unique=False)
    op.create_index(op.f('ix_library_media_library_id'), 'library_media', ['library_id'], unique=False)
    op.create_table('library_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='ck_library_memberships_role'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'user_id', name='uq_library_memberships_library_user')
    )
    op.create_index('idx_library_memberships_library', 'library_memberships', ['library_id'], unique=False)
    op.create_index('idx_library_memberships_user', 'library_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_library_memberships_library_id'), 'library_memberships', ['library_id'], unique=False)
    op.create_index(op.f('ix_library_memberships_user_id'), 'library_memberships', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effective_model_id', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id', 'created_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_messages_user', 'messages', ['user_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('object_library_visibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('shared_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("object_type IN ('highlight', 'annotation', 'conversation', 'message')", name='ck_object_visibility_type'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'object_id', 'library_id', name='uq_object_visibility_object_library')
    )
    op.create_index('idx_object_visibility_library', 'object_library_visibility', ['library_id'], unique=False)
    op.create_index('idx_object_visibility_object', 'object_library_visibility', ['object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_object_library_visibility_library_id'), 'object_library_visibility', ['library_id'], unique=False)
    op.create_table('readers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uq_readers_user_document')
    )
    op.create_index('idx_readers_document', 'readers', ['document_id'], unique=False)
    op.create_index('idx_readers_user', 'readers', ['user_id'], unique=False)
    op.create_index(op.f('ix_readers_document_id'), 'readers', ['document_id'], unique=False)
    op.create_index(op.f('ix_readers_user_id'), 'readers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readers_user_id'), table_name='readers')
    op.drop_index(op.f('ix_readers_document_id'), table_name='readers')
    op.drop_index('idx_readers_user', table_name='readers')
    op.drop_index('idx_readers_document', table_name='readers')
    op.drop_table('readers')
    op.drop_index(op.f('ix_object_library_visibility_library_id'), table_name='object_library_visibility')
    op.drop_index('idx_object_visibility_object', table_name='object_library_visibility')
    op.drop_index('idx_object_visibility_library', table_name='object_library_visibility')
    op.drop_table('object_library_visibility')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_messages_user', table_name='messages', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_messages_conversation', table_name='messages', postgresql_where='deleted_at IS NULL')
    op.drop_table('messages')
    op.drop_index(op.f('ix_library_memberships_user_id'), table_name='library_memberships')
    op.drop_index(op.f('ix_library_memberships_library_id'), table_name='library_memberships')
    op.drop_index('idx_library_memberships_user', table_name='library_memberships')
    op.drop_index('idx_library_memberships_library', table_name='library_memberships')
    op.drop_table('library_memberships')
    op.drop_index(op.f('ix_library_media_library_id'), table_name='library_media')
    op.drop_index('idx_library_media_media', table_name='library_media')
    op.drop_index('idx_library_media_library', table_name='library_media')
    op.drop_table('library_media')
    op.drop_index(op.f('ix_annotations_user_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_highlight_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_chunk_id'), table_name='annotations')
    op.drop_index('idx_annotations_user', table_name='annotations', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_annotations_highlight', table_name='annotations', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_annotations_chunk', table_name='annotations', postgresql_where='deleted_at IS NULL')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_thought_chunks_user_id'), table_name='thought_chunks')
    op.drop_index('idx_thought_chunks_user', table_name='thought_chunks')
    op.drop_index('idx_thought_chunks_object', table_name='thought_chunks')
    op.drop_table('thought_chunks')
    op.drop_index(op.f('ix_links_created_by_user_id'), table_name='links')
    op.drop_index('idx_links_target', table_name='links')
    op.drop_index('idx_links_source', table_name='links')
    op.drop_index('idx_links_creator', table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_libraries_user_id'), table_name='libraries')
    op.drop_index('idx_libraries_user', table_name='libraries')
    op.drop_index('idx_libraries_public', table_name='libraries', postgresql_where='is_public = TRUE')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_highlights_user_id'), table_name='highlights')
    op.drop_index('idx_highlights_user', table_name='highlights', postgresql_where='NOT is_hidden AND deleted_at IS NULL')
    op.drop_index('idx_highlights_transcript', table_name='highlights', postgresql_where="anchor_type = 'transcript' AND deleted_at IS NULL")
    op.drop_index('idx_highlights_pdf', table_name='highlights', postgresql_where="anchor_type = 'pdf' AND deleted_at IS NULL")
    op.drop_index('idx_highlights_media', table_name='highlights', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_highlights_anchor_type', table_name='highlights')
    op.drop_table('highlights')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index('idx_documents_user', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents', postgresql_where="status != 'ready' AND deleted_at IS NULL")
    op.drop_index('idx_documents_embedding_status', table_name='documents', postgresql_where="embedding_status != 'ready' AND deleted_at IS NULL")
    op.drop_index('idx_documents_content_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index('idx_conversations_user', table_name='conversations', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_conversations_public', table_name='conversations', postgresql_where='is_public = TRUE AND deleted_at IS NULL')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_external_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_external_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_metadata_chunks_entity', table_name='metadata_chunks')
    op.drop_table('metadata_chunks')
    op.drop_index('idx_content_chunks_media', table_name='content_chunks')
    op.drop_table('content_chunks')
    # ### end Alembic commands ###
